// Challenge Coding Qno:23
var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car !== 'subaru'? I predict True.");
console.log(car !== 'subaru');
console.log("Is car == 'ford'? I predict True.");
console.log(car == 'ford');
console.log("Is car !== 'ford'? I predict True.");
console.log(car !== 'ford');
console.log("Is car == 'Toyota'? I predict True.");
console.log(car == 'Toyota');
console.log("Is car !== 'Toyota'? I predict True.");
console.log(car !== 'Toyota');
console.log("Is car == 'Suzuki'? I predict True.");
console.log(car == 'Suzuki');
console.log("Is car !== 'Suzuki'? I predict True.");
console.log(car !== 'Suzuki');
console.log("Is car == 'BMW'? I predict True.");
console.log(car == 'BMW');
console.log("Is car !== 'BMW'? I predict True.");
console.log(car !== 'BMW');
